# =============================================================================
# HYPERSONIC STEALTH RCS MODULE (SESI FRAMEWORK)
# SUPER DNS ONE Cluster / ONE Ecosystem
# =============================================================================
# Description: A fully differentiable, production-optimized module for computing 
# Radar Cross Section (RCS) attenuation via topologically-active plasma interfaces.
# Resolves the Zeno Trap using Double-Exponential Extreme-Value Statistics and 
# supports multi-modal propulsion signatures (Traditional vs. High-Yield Battery).
# =============================================================================
# =============================================================================
# Developer    : PAI , Yoon A Limsuwan / MSPS NETWORK
# ORCID        : 0009-0008-2374-0788
# GitHub       : yoonalimsuwan
# Contact      : msps4u@gmail.com
# License      : MIT
# Year         : 2026
# =============================================================================


import torch
import torch.nn as nn
from typing import Tuple, Dict

__all__ = ["DifferentiableHypersonicStealthRCS"]

class DifferentiableHypersonicStealthRCS(nn.Module):
    """
    Simulates the electromagnetic attenuation (stealth) of a hypersonic vehicle 
    by modeling the plasma sheath as a disordered medium undergoing stochastic 
    topological transitions (Nucleation, Merging, Branching).
    """
    def __init__(
        self, 
        c1: float = 1.0, 
        ste_tau: float = 0.05,
        base_dissipation: float = 0.1,
        c_topo_max: float = 0.99  # Maximum energy dissipation per jump C_{topo}
    ) -> None:
        super().__init__()
        # Geometric constant of the domain for the extreme-value bound
        self.c1 = c1
        # Temperature parameter for Straight-Through Estimator (STE) relaxation
        self.ste_tau = ste_tau
        # Baseline structural dissipation
        self.base_dissipation = base_dissipation
        # Upper bound for energy bounding at jumps to satisfy global energy inequality
        self.c_topo = c_topo_max

    @torch.jit.export
    def compute_extreme_value_bound(
        self, 
        delta_e: torch.Tensor, 
        sigma_sq: torch.Tensor, 
        dt: float
    ) -> torch.Tensor:
        """
        Computes the Double-Exponential (Gumbel-type) probability bound for 
        topological events in a disordered medium.
        """
        # Exponent = \Delta E / (\sigma^2 \delta t)
        # Clamped to prevent arithmetic overflow (cost reduction & stability)
        exponent = torch.clamp(delta_e / (sigma_sq * dt + 1e-12), max=50.0)
        
        # P(\tau_{k+1} - \tau_k < \delta t) <= exp[-C1 * exp(exponent)]
        prob_bound = torch.exp(-self.c1 * torch.exp(exponent))
        return prob_bound

    def forward(
        self, 
        incident_em_field: torch.Tensor, 
        delta_e_field: torch.Tensor,
        thermal_variance: torch.Tensor,
        propulsion_em_coupling: torch.Tensor,
        dt: float,
        is_battery_powered: bool = False
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Calculates the attenuated RCS signature after interacting with the 
        topologically-active plasma interface.
        
        Args:
            incident_em_field: 3D/4D Tensor of the incoming radar wave.
            delta_e_field: The activation energy barrier (\Delta E) of the plasma.
            thermal_variance: Baseline fluctuation (\sigma^2) from thermodynamics.
            propulsion_em_coupling: EM noise generated by the engine/battery.
            dt: Time step size.
            is_battery_powered: Boolean flag to route extreme EM fluctuations.
            
        Returns:
            attenuated_em_field: The radar signature escaping the plasma sheath.
            dissipation_energy: The energy absorbed by the topological jumps.
        """
        # 1. Modulate Fluctuation Variance based on Propulsion Type
        # Battery systems inject massive localized EM noise into the disordered medium,
        # drastically altering the random interface fluctuations.
        if is_battery_powered:
            # Non-linear coupling for extreme battery EMF
            sigma_sq = thermal_variance + (propulsion_em_coupling ** 2)
        else:
            # Traditional combustion (primarily thermal/acoustic coupling)
            sigma_sq = thermal_variance + (0.1 * propulsion_em_coupling)

        # 2. Compute No-Zeno Probability Bound
        prob_bound = self.compute_extreme_value_bound(delta_e_field, sigma_sq, dt)

        # 3. Differentiable Stochastic Jump Application (Straight-Through Estimator)
        # We model the topological operators (N, M, B) as discrete extreme events.
        rand_tensor = torch.rand_like(prob_bound)
        
        # Continuous relaxation for backpropagation (Autograd graph preserved)
        soft_mask = torch.sigmoid((prob_bound - rand_tensor) / self.ste_tau)
        
        # Hard binary mask for the piecewise operational construction
        hard_mask = (prob_bound > rand_tensor).float()
        
        # STE Trick: Forward = Hard (discrete), Backward = Soft (continuous)
        jump_mask = hard_mask.detach() - soft_mask.detach() + soft_mask

        # 4. Energy Dissipation via Topological Jumps
        # According to the Global Energy Inequality across topological jumps,
        # E(\Gamma(T_k^+)) - E(\Gamma(T_k^-)) <= C_{topo}
        # The incident EM energy is absorbed by the creation/merging of plasma structures.
        
        # Calculate dynamic dissipation factor. 
        # Base dissipation + spike dissipation at jump locations.
        jump_dissipation = self.c_topo * jump_mask * (sigma_sq / (sigma_sq + 1.0))
        total_dissipation = torch.clamp(self.base_dissipation + jump_dissipation, 0.0, 0.999)

        # 5. Apply Stealth Attenuation to Incident Radar Field
        attenuated_em_field = incident_em_field * (1.0 - total_dissipation)

        # Calculate the actual energy quantity absorbed by the interface
        dissipated_energy = (incident_em_field ** 2) * total_dissipation

        return attenuated_em_field, dissipated_energy
